### PR TITLE
will add detailed commit

### PR DESCRIPTION
**Pull request by tswhitworth**
Database Models ✅
- https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/CartBuilder/models.py
- The Allergies Model is still in the Database for now, but I think allergies are going to be outside of the scope of this project.
- I would say they are in scope but the data that we are using doesn't have relationships between foods and allergies, and if that isn't embedded into the data it's really hard to do dynamically after the factor.

[ _ ] - This week during class, let's decide whether allergies are outside the scope or not. 

Database Accessor and Modifier Methods ✅
- I constructed class methods and functions that will be used to manipulate the database fields.
- for example,  get_popular_recipe is used to retrieve a list of the most popular recipes, based on the number of times they appear in users' favorite recipes list.
- This method can then be called in the views.py file to hand off the data to the front end.

MockData ✅
MockData from @robert-daniels is now structured in a Mock Database that we will pull from later when we are generating users, this will enable us to have a more organic production database. 

CSV that we are ripping -> https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/recipe_ingredients.csv

MockData Fields in Model.py -> https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/CartBuilder/models.py#L140

MockData CSV parser that I wrote that rips the CSV, and inserts it into database -> https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/CartBuilder/management/commands/import_csv.py 

I made the CSV parser into a django command, usage is below:
python3 manage.py import_csv -- help
python3 manage.py import_csv

Basic View structure ✅ 
- My goal here was just to get a skeleton going for a few pages, making it so we could start getting a bigger picture of what's going on.
- During class this week @robert-daniels we need to integrate React in the Django build steps.
- views.py -> https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/CartBuilder/views.py
- Right now, every page except Home is just a static page, but I've added some dynamic calls to the home page.
- home.html -> https://github.com/robert-daniels/CartBuilder/blob/main-django-branch/CartBuilderApplication/templates/home.html

Sorry for the large commit all at once, I was having some issues with git over the past week on my MacBook but have them sorted out now.

### CODE REVIEW

**Comment by tswhitworth** [comment]
Here's a query you can copy and paste into your python interpreter to prove that we have data in our SQLite db.

>>> from CartBuilder.models import MockIngredient, MockRecipe, MockRecipeIngredient, MockCookingInstruction
>>> MockRecipe.objects.filter(m_recipe_name='Jiffy Beef Stroganoff').exists()
True

**Comment by robert-daniels** [comment]
Perfect! @tswhitworth Looking around at how best to harmonize, I might try this method: https://medium.com/codex/how-to-integrate-react-and-django-framework-in-a-simple-way-c8b90f3ce945. Just pushed branch react-django-harmonize, though it hasn't been tested or worked on. (Can't run scripts on current tower, need home computer)

**Comment by tswhitworth** [comment]
As we've been talking about in our pm's @robert-daniels there are a few different approaches to running Django/React applications. 

Right now the way we have our Django project setup is called: "server-first architecture". The article that you posted wants us to have our project setup in a Client-first architecture. And unlike the ad-hoc path to a server-first setup, client-first architectures require a deliberate intention from the start of the project. 

This is my fault, and I hadn't considered this when I started. It would require a fair amount of backtracking to achieve this client-first architecture. The client-first setups also come with substantial tradeoffs.

The most important one in my opinion is that by moving the entire UI to the JavaScript framework, Django's built-in support for templates, forms, and other front-end goodies are basically thrown out the window. In many cases, these need to be rebuilt within the front-end framework.

details about these different architecture types: read: https://www.saaspegasus.com/guides/modern-javascript-for-django-developers/client-server-architectures/

As a result, simple tasks can become much more complicated in a client-first setup. For example, building a page to update a data model will typically involve creating a Serializer class, an API endpoint, and custom front-end code to render a form and handle validation when all you really wanted was a 5-line [ModelForm](https://docs.djangoproject.com/en/3.0/topics/forms/modelforms/).

We spoke a little bit about how we could go about implementing a hybrid architecture with something like Vue.js or React but we had to set up React in a different way than the article you post above. below you can read about that. 

read: https://www.saaspegasus.com/guides/modern-javascript-for-django-developers/integrating-django-react/ 

I hope these articles can help answer some of the questions you have about the different architectures and our options.

As I said before, I think Vue.js could be the easiest to integrate, but it sounds like we could also do it in React with the Hybrid-Architecture. The second article goes into more depth about that.

**Comment by robert-daniels** [comment]
Looking at their template structure, reasonably confident we can simply build off what is proposed here! Was there meant to be a settings.py file in this PR? Having some trouble with the runserver command

**Comment by tswhitworth** [comment]
I just went back to look at my code, and I just realized I deleted the entire CartBuilderApplication directory (directory that contained settings.py, among many important files) right before I did my commit. Luckily, I was able to undo that deletion of the directory. 

Do you think it would be best for me to upload it on a new branch? @robert-daniels

**Comment by tswhitworth** [comment]
@robert-daniels I added the missing files, and confirmed that it builds ✅
https://github.com/robert-daniels/CartBuilder/pull/20/commits/8efa425284e90e66436fc5cd1ffbc7b025c2936e

**Review by yassine022 — APPROVED** [review]

**Pull request merged**
