### PR TITLE
Test vue factory testing

### PR DESCRIPTION
**Pull request by tswhitworth**
added README.md and updated csv_parser and models.py file so that we are parsing cooking instructions and saving them to our db.

### CODE REVIEW

**Comment by tswhitworth** [comment]
@robert-daniels I owe you a coffee at some point. I think I can't untangle these merge conflicts. 

It's fine if you can't work on this til the 30th or later like you had talked about. I'm just putting this on your radar, or I'll never remember in the future.

**Comment by tswhitworth** [comment]
Just a side note. We want to keep main's db.sqlite3, not test-vue-factory-branch's db.sqlite3 file (this binary file is what is causing the merge conflict). I don't have a way of regenerating your simple database, so we'll just keep your db file in there until I reimplement everything your simple database is doing so then we are just calling my function in models.py rather than a segrigated part of the program.

Which I'm in the process of reimplenting in

**Comment by robert-daniels** [comment]
Assigning to my workflow, will resolve.

**Comment by robert-daniels** [comment]
Actually, scratch that. Did a rebase, and tested. @tswhitworth , at your convenience please git pull the changes to your local to verify merging was done to your specs. If so, PR should be reviewed and merged.

**Review by yassine022 — APPROVED** [review]

**Pull request merged**
