### PR TITLE
Test vue factory testing

### PR DESCRIPTION
**Pull request by tswhitworth**

### CODE REVIEW

**Comment by robert-daniels** [comment]
@tswhitworth , looks like merge conflicts on this branch re: migration numbers

**Comment by tswhitworth** [comment]
@robert-daniels yes it looks like there are some conflicts but we should be able to just delete the migrations in main right? and then just use the migrations that we have in this branch? 

I'm looking into how I can solve this, but I have the db the way I want it in this branch, and I just want to make sure we don't revert these changes. (I should be better at git but I'm getting there, I should try downloading the GUI client you were talking about... I've just been reluctant to not use the CLI)

**Review by robert-daniels — CHANGES_REQUESTED** [review]
Freezing PR, merge conflicts with migration. Defer to backend. To resolve this weekend

**Comment by robert-daniels** [comment]
@tswhitworth , this should be untangled. To verify, highly recommend branching your local and then git switch main / git pull to verify if main is behaving as you had originally PR'd.

**Comment by tswhitworth** [comment]
@robert-daniels Thank you for untangling that.

Adding testing and validation is a great idea, and I think we will be able to easily weave it into our user creation process.

I wrote a detailed commit about my gen_users command, which uses factory(s) to generate our users [here](https://github.com/robert-daniels/CartBuilder/issues/32) and the error that I'm stuck on. It's fully implemented, but obviously something small is wrong that is making it not work. I'm still working through it.

So we don't have real data in the db yet, but we are so close. Check it out when you have a chance.

**Review by robert-daniels — COMMENTED** [review]
clear freeze -rd3

**Pull request merged**
